### ISSUE TITLE
Spark에 job을 실행 시키면 설정과 달리 core를 냅다 다 가져감

### ISSUE THREAD

**Issue by RicardoKim** [RicardoKim/AndroidMonitoringSystem#18]

**Comment by RicardoKim** [comment]
# Spark UI

<div class="row" style="box-sizing: border-box; display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; color: rgb(33, 37, 41); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col-12" style="box-sizing: border-box; position: relative; width: 1455px; padding-right: 15px; padding-left: 15px; flex: 0 0 100%; max-width: 100%;"><ul class="list-unstyled" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; padding-left: 0px; list-style: none;"><li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">URL:</strong><span> </span>spark://cbf2fb37f96d:7077</li><li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Alive Workers:</strong><span> </span>2</li><li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Cores in use:</strong><span> </span>40 Total, 32 Used</li><li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Memory in use:</strong><span> </span>8.0 GiB Total, 8.0 GiB Used</li><li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Resources in use:</strong></li><li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Applications:</strong><span> </span>2<span> </span><a href="http://localhost:8080/#running-app" style="box-sizing: border-box; color: rgb(0, 136, 204); text-decoration: none; background-color: transparent;">Running</a>, 0<span> </span><a href="http://localhost:8080/#completed-app" style="box-sizing: border-box; color: rgb(0, 136, 204); text-decoration: none; background-color: transparent;">Completed</a></li><li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Drivers:</strong><span> </span>0 Running, 0 Completed</li><li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bolder;">Status:</strong><span> </span>ALIVE</li></ul></div></div><div class="row" style="box-sizing: border-box; display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; color: rgb(33, 37, 41); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col-12" style="box-sizing: border-box; position: relative; width: 1455px; padding-right: 15px; padding-left: 15px; flex: 0 0 100%; max-width: 100%;"><span class="collapse-aggregated-workers collapse-table" onclick="collapseTable('collapse-aggregated-workers','aggregated-workers')" style="box-sizing: border-box; cursor: pointer;"><h4 style="box-sizing: border-box; margin: 0.75rem 0px; font-weight: 700; line-height: 1.2; font-size: 1.25rem;"><span class="collapse-table-arrow arrow-open" style="box-sizing: border-box; width: 0px; height: 0px; border-left: 5px solid transparent; border-right: 5px solid transparent; border-top: 5px solid rgb(0, 136, 204); display: inline-block; margin-bottom: 2px;"></span><span> </span><a style="box-sizing: border-box; color: rgb(0, 136, 204); text-decoration: none; background-color: transparent;">Workers (2)</a></h4></span><div class="aggregated-workers collapsible-table" style="box-sizing: border-box;">

Worker Id | Address | State | Cores | Memory | Resources
-- | -- | -- | -- | -- | --
worker-20230924080914-192.168.0.2-35917 | 192.168.0.2:35917 | ALIVE | 20 (16 Used) | 4.0 GiB (4.0 GiB Used) |  
worker-20230924080914-192.168.0.4-35817 | 192.168.0.4:35817 | ALIVE | 20 (16 Used) | 4.0 GiB (4.0 GiB Used) |  

</div></div></div><div style="box-sizing: border-box; color: rgb(33, 37, 41); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><div class="row" style="box-sizing: border-box; display: flex; flex-wrap: wrap; margin-right: -15px; margin-left: -15px; color: rgb(33, 37, 41); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col-12" style="box-sizing: border-box; position: relative; width: 1455px; padding-right: 15px; padding-left: 15px; flex: 0 0 100%; max-width: 100%;"><span id="completed-app" class="collapse-aggregated-completedApps collapse-table" onclick="collapseTable('collapse-aggregated-completedApps',
                'aggregated-completedApps')" style="box-sizing: border-box; cursor: pointer;"><h4 style="box-sizing: border-box; margin: 0.75rem 0px; font-weight: 700; line-height: 1.2; font-size: 1.25rem;"><span class="collapse-table-arrow arrow-open" style="box-sizing: border-box; width: 0px; height: 0px; border-left: 5px solid transparent; border-right: 5px solid transparent; border-top: 5px solid rgb(0, 136, 204); display: inline-block; margin-bottom: 2px;"></span><span> </span><a style="box-sizing: border-box; color: rgb(0, 136, 204); text-decoration: none; background-color: transparent;">Completed Applications (0)</a></h4></span><div class="aggregated-completedApps collapsible-table" style="box-sizing: border-box;"></div></div></div><br class="Apple-interchange-newline">URL: spark://cbf2fb37f96d:7077
Alive Workers: 2
Cores in use: 40 Total, 32 Used
Memory in use: 8.0 GiB Total, 8.0 GiB Used
Resources in use:
Applications: 2 [Running](http://localhost:8080/#running-app), 0 [Completed](http://localhost:8080/#completed-app)
Drivers: 0 Running, 0 Completed
Status: ALIVE
 Workers (2)
Worker Id	Address	State	Cores	Memory	Resources
[worker-20230924080914-192.168.0.2-35917](http://192.168.0.2:8081/)	192.168.0.2:35917	ALIVE	20 (16 Used)	4.0 GiB (4.0 GiB Used)	
[worker-20230924080914-192.168.0.4-35817](http://192.168.0.4:8081/)	192.168.0.4:35817	ALIVE	20 (16 Used)	4.0 GiB (4.0 GiB Used)	
 Running Applications (2)
Application ID	Name	Cores	Memory per Executor	Resources Per Executor	Submitted Time	User	State	Duration
[app-20230924081032-0001](http://localhost:8080/app/?appId=app-20230924081032-0001)[(kill)](http://localhost:8080/#)	[AndroidProcessTopicConsumer](http://a5debd3a257b:4040/)	0	1024.0 MiB		2023/09/24 08:10:32	spark	WAITING	8 s
[app-20230924081025-0000](http://localhost:8080/app/?appId=app-20230924081025-0000)[(kill)](http://localhost:8080/#)	[AndroidMemoryTopicConsumer](http://77ba8bb25467:4040/)	32	1024.0 MiB		2023/09/24 08:10:25	spark	RUNNING	15 s
 Completed Applications (0)

**Comment by RicardoKim** [comment]
# docker-compose yml

```yml
spark:
    image: docker.io/bitnami/spark:3.4
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      - app_network

  spark-worker-1:
    image: docker.io/bitnami/spark:3.4
    volumes:
       - ./spark:/opt/spark-script
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=20
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    command: >
      bash -c "
        pip install pymongo &&
        spark-submit --executor-cores 4 --executor-memory 1g --num-executors 1 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1 --master spark://spark:7077 /opt/spark-script/spark_consumer.py
      "
    networks:
      - app_network

  spark-worker-2:
    image: docker.io/bitnami/spark:3.4
    volumes:
       - ./spark:/opt/spark-script
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=20
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    command: >
      bash -c "
        pip install pymongo &&
        spark-submit --executor-cores 4 --executor-memory 1g --num-executors 1 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1 --master spark://spark:7077 /opt/spark-script/spark_memory_consumer.py
      "
    networks:
      - app_network
```
